// Expanded to 20 products and 3 bundles (mix of affiliate and direct)
export const products = [
  { id: 1, name: "Cosrx Low pH Cleanser", price: 1200, type: "product", affiliate: false },
  { id: 2, name: "Beauty of Joseon Sunscreen", price: 1800, type: "product", affiliate: false },
  { id: 3, name: "Cerave Moisturizing Cream", price: 2200, type: "product", affiliate: false },
  { id: 4, name: "Avene Cleanance Gel", price: 1500, type: "product", affiliate: false },
  { id: 5, name: "Epiduo Gel", price: 2500, type: "product", affiliate: false },
  { id: 6, name: "Clindamycin Lotion", price: 900, type: "product", affiliate: false },
  { id: 7, name: "Hydrocortisone Cream", price: 700, type: "product", affiliate: false },
  { id: 8, name: "Etude House SoonJung pH 5.5 Foam", price: 1300, type: "product", affiliate: false },
  { id: 9, name: "Neutrogena Hydro Boost", price: 2000, type: "product", affiliate: false },
  { id: 10, name: "Simple Micellar Water", price: 800, type: "product", affiliate: false },
  { id: 11, name: "Jumia Skincare Bundle", price: 3500, type: "bundle", affiliate: true, link: "https://www.jumia.co.ke/" },
  { id: 12, name: "Glow Up Bundle", price: 4000, type: "bundle", affiliate: false },
  { id: 13, name: "Acne Control Bundle", price: 4200, type: "bundle", affiliate: false },
  { id: 14, name: "Bioderma Sensibio H2O", price: 1600, type: "product", affiliate: false },
  { id: 15, name: "Jumia Vitamin C Serum", price: 2100, type: "product", affiliate: true, link: "https://www.jumia.co.ke/" },
  { id: 16, name: "La Roche-Posay Effaclar Duo+", price: 2600, type: "product", affiliate: false },
  { id: 17, name: "Nivea Perfect & Radiant", price: 950, type: "product", affiliate: false },
  { id: 18, name: "Jumia K-Beauty Bundle", price: 3700, type: "bundle", affiliate: true, link: "https://www.jumia.co.ke/" },
  { id: 19, name: "Cleansing Oil", price: 1100, type: "product", affiliate: false },
  { id: 20, name: "Snail Mucin Essence", price: 2300, type: "product", affiliate: false },
  { id: 21, name: "Sensitive Skin Bundle", price: 3900, type: "bundle", affiliate: false },
];
